"""add license

Revision ID: 06f570dd7331
Revises: 4fa94bb5be6a
Create Date: 2018-02-14 08:25:45.923937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f570dd7331'
down_revision = '4fa94bb5be6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('doctor', sa.Column('license', sa.String(length=255), nullable=True))
    op.add_column('doctor', sa.Column('type_of_patient', sa.String(length=255), nullable=True))
    op.add_column('patient', sa.Column('feeling', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('sad', sa.String(), nullable=True))
    op.drop_column('patient', 'com')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('com', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'sad')
    op.drop_column('patient', 'mood')
    op.drop_column('patient', 'feeling')
    op.drop_column('doctor', 'type_of_patient')
    op.drop_column('doctor', 'license')
    op.drop_column('doctor', 'experience')
    # ### end Alembic commands ###
