"""add the image table

Revision ID: 4fa94bb5be6a
Revises: 0a9e4402b908
Create Date: 2018-02-13 14:53:53.340415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa94bb5be6a'
down_revision = '0a9e4402b908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctalks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctalks')
    # ### end Alembic commands ###
