"""add the image table

Revision ID: 8d003abb61f4
Revises: 9172123cdc36
Create Date: 2018-02-14 15:32:35.531076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d003abb61f4'
down_revision = '9172123cdc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['doctalks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('doctor', 'type_of_patient')
    op.drop_column('doctor', 'phone_number')
    op.drop_column('doctor', 'bio')
    op.drop_column('doctor', 'license')
    op.drop_column('doctor', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('license', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('type_of_patient', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('docdetails')
    # ### end Alembic commands ###
