"""add the image table

Revision ID: 9172123cdc36
Revises: 06f570dd7331
Create Date: 2018-02-14 11:12:22.022061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9172123cdc36'
down_revision = '06f570dd7331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('bio', sa.String(length=255), nullable=True))
    op.drop_column('doctor', 'experience')
    op.drop_column('doctor', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('doctor', sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('doctor', 'bio')
    # ### end Alembic commands ###
