"""add the image table

Revision ID: b86eb6e708ed
Revises: 8d003abb61f4
Create Date: 2018-02-14 15:46:24.591945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86eb6e708ed'
down_revision = '8d003abb61f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('docdetails_doc_id_fkey', 'docdetails', type_='foreignkey')
    op.create_foreign_key(None, 'docdetails', 'doctor', ['doc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docdetails', type_='foreignkey')
    op.create_foreign_key('docdetails_doc_id_fkey', 'docdetails', 'doctalks', ['doc_id'], ['id'])
    # ### end Alembic commands ###
